/**
  You need to create an express HTTP server in Node.js which will handle the logic of a todo list app.
  - Don't use any database, just store all the data in an array to store the todo list data (in-memory)
  - Hard todo: Try to save responses in files, so that even if u exit the app and run it again, the data remains (similar to databases)

  Each todo has a title and a description. The title is a string and the description is a string.
  Each todo should also get an unique autogenerated id every time it is created
  The expected API endpoints are defined below,
  1.GET /todos - Retrieve all todo items
    Description: Returns a list of all todo items.
    Response: 200 OK with an array of todo items in JSON format.
    Example: GET http://localhost:3000/todos

  2.GET /todos/:id - Retrieve a specific todo item by ID
    Description: Returns a specific todo item identified by its ID.
    Response: 200 OK with the todo item in JSON format if found, or 404 Not Found if not found.
    Example: GET http://localhost:3000/todos/123

  3. POST /todos - Create a new todo item
    Description: Creates a new todo item.
    Request Body: JSON object representing the todo item.
    Response: 201 Created with the ID of the created todo item in JSON format. eg: {id: 1}
    Example: POST http://localhost:3000/todos
    Request Body: { "title": "Buy groceries", "completed": false, description: "I should buy groceries" }

  4. PUT /todos/:id - Update an existing todo item by ID
    Description: Updates an existing todo item identified by its ID.
    Request Body: JSON object representing the updated todo item.
    Response: 200 OK if the todo item was found and updated, or 404 Not Found if not found.
    Example: PUT http://localhost:3000/todos/123
    Request Body: { "title": "Buy groceries", "completed": true }

  5. DELETE /todos/:id - Delete a todo item by ID
    Description: Deletes a todo item identified by its ID.
    Response: 200 OK if the todo item was found and deleted, or 404 Not Found if not found.
    Example: DELETE http://localhost:3000/todos/123

    - For any other route not defined in the server return 404

  Testing the server - run `npm run test-todoServer` command in terminal
 */

const fs = require("fs");
const path = require("path");
const express = require("express");
const cors = require("cors");
const bodyParser = require("body-parser");
const app = express();

app.use(bodyParser.json());
// app.use(cors());

const port = 3000;
let ctr = 0;

app.get("/todos", (req, res) => {
  fs.readFile("todos.json", "utf8", (err, data) => {
    if (err) throw err;
    res.json(JSON.parse(data));
  });
});

app.post("/todos", (req, res) => {
  var todoList = {
    id: ctr,
    title: req.body.title,
    description: req.body.description,
  };
  ctr += 1;
  fs.readFile("todos.json", "utf8", (err, data) => {
    if (err) throw err;
    var todo = JSON.parse(data);
    todo.push(todoList);
    fs.writeFile("todos.json", JSON.stringify(todo), (err) => {
      if (err) throw err;
      res.status(201).json(todoList);
    });
  });
});

function findIndex(arr, id) {
  for (var i = 0; i < arr.length; i++) {
    if (arr[i].id === id) return i;
  }
  return -1;
}

app.delete("/todos/:id", (req, res) => {
  const idToDelete = parseInt(req.params.id); // get the id
  fs.readFile("todos.json", "utf8", (err, data) => {
    if (err) throw err;
    const parsedTodos = JSON.parse(data);
    if (findIndex(parsedTodos, idToDelete) === -1) {
      res.sendStatus(404);
    } else {
      parsedTodos.splice(findIndex(parsedTodos, idToDelete), 1);
      fs.writeFile("todos.json", JSON.stringify(parsedTodos), (err) => {
        if (err) throw err;
        res.status(201).json(parsedTodos);
      });
    }
  });
});

app.get("/", (req, res) => {
  res.sendFile(path.join(__dirname, "index.html"));
});

app.listen(port, () => {
  console.log("Server started on http://localhost:3000");
});
